### ISSUE TITLE
Please fix your X11 implemantation

### ISSUE THREAD

**Issue by brummer10** [x42/tuna.lv2#12]
so that your plug behave smooth on qt based host's as well.

**Comment by x42** [comment]
Must be a host issue. This  is a perfectly good X11 GUI, that works fine standalone
And works correctly in jalv.qt4.

Most likely an issue with suil's x11_in_qt5 not honoring X11SizeHints correctly, similar to the issue that was fixed in  https://github.com/lv2/suil/pull/13 for gtk.

This is not under my control as plugin author.
